#!/bin/bash
#SBATCH --job-name=GDBImp_allSamps_ch22_27
#SBATCH -A highmem
#SBATCH -N 1
#SBATCH -n 128
#SBATCH -t 24:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=sparks35@purdue.edu

module purge
PROJHOME=/scratch/bell/sparks35/GL_Pink_Salmon
HAPCALLS=/scratch/bell/sparks35/GL_Pink_Salmon/data/seqs/aligned_reads_OgorEven_v1.0/06_hap_calls

while read -a line
do
/home/sparks35/gatk-4.2.2.0/gatk --java-options "-Xmx128g -Xms128g" GenomicsDBImport \
-V $HAPCALLS/${line[0]}_LAO_161_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_162_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_163_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_164_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_165_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_170_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_171_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_173_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_177_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_182_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_183_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_185_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_186_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_187_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_188_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_189_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_191_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_192_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_193_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_194_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_195_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_198_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_199_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_201_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_203_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_204_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_205_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_206_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAO_207_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_101_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_105_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_112_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_113_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_125_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_136_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_159_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_160_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_187_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_189_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_191_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_201_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_205_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_206_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_210_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_226_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_228_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_244_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_247_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_259_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_264_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_270_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_271_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_290_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_304_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_315_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_316_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_318_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_328_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_006_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_012_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_024_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_030_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_036_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_042_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_053_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_056_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_057_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_058_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_059_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_062_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_064_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_065_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_071_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_076_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_077_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_080_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_081_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_082_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_083_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_086_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_087_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_088_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_089_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_093_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_095_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_098_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_099_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_LAE_100_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_003_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_006_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_007_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_008_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_009_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_011_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_012_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_013_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_014_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_015_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_016_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_017_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_018_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_019_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_020_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_021_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_022_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_024_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_025_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_026_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_028_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_030_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_031_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_033_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_035_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_036_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_038_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_039_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_046_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_048_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_331_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_104_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_110_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_111_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_134_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_139_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_153_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_175_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_179_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_194_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_203_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_252_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_302_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_308_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_310_OgorEven.g.vcf.gz \
-V $HAPCALLS/${line[0]}_STL_319_OgorEven.g.vcf.gz \
--genomicsdb-workspace-path $PROJHOME/data/seqs/aligned_reads_OgorEven_v1.0/07_genomicsDB/all_samps/${line[0]}_genomicsDatabase \
-L ${line[0]} \
--batch-size 30 \
--tmp-dir tmpdir \
--genomicsdb-shared-posixfs-optimizations true \
--reader-threads 4 &
  done < $PROJHOME/data/seqs/aligned_reads_OgorEven_v1.0/chromosome_list_22_27.txt
wait
